### ISSUE TITLE
Zooming the mood bar makes part of it transparent

### ISSUE THREAD

**Issue by ghost** [Killface1980/RW_ColonistBarKF#3]
The green goes from fairly solid to invisible once you've fully zoomed in.

Also, as an aside... the mood bar just doesn't look very good. The way it looked in A14 was much better.

**Comment by tommargar** [comment]
It's behaving as it should, and I don't see the advantage of a constantly solid filled bar.

Might add an option in the next version

**Comment by ghost** [comment]
Can you make it look more like the moodbar from MuzzyUtils?

**Comment by tommargar** [comment]
I'm changing the colors + opacity option. but to be honest, I don't like the look of the MuzzyUtils. 
Since I first added the mood bars, the only request was to make it look like muzzy's. So yes the mood bar needs a redesign, but it should differ from MuzzyUtils.

**Comment by ghost** [comment]
Huh. What's wrong with how MuzzyUtils looks? It always seemed pretty ideal to me.

**Comment by tommargar** [comment]
It clutters the icon. there is absolutely no need for filling the whole background, with fat colonists blocking the complete lower half. it's supposed to show you just the status, not act as a constant moving eyecatcher.

With the weapon icon added, this clutters even more plus overlays the lower half, see the fat colonists. 

One guy suggested to make both the background, the weapon icon + the full mood colors visible - how? this is not how colors or usability works. 

I adapted the function, but I see it as a minor feature. Muzzy has 10,000 subscribers, and the few that use my bar constantly request to make mine look exactly like his. I refuse.

My bar fills the bad mood till the next break threshold. I suggest using the minified version as it holds all the information in 1/3 of a rect instead of filling it out 

![image](https://cloud.githubusercontent.com/assets/16738568/18521698/84133578-7aad-11e6-9217-c5a6d945715b.png)

**Comment by ghost** [comment]
Quite frankly I need something eye-catching. My eyesight is far too poor to use the minified version.

**Comment by tommargar** [comment]
that's why the icons can be zoomed. 

also, the whole icons switches color once a mental break threshold is reached. even the small icon is sufficient to see if it's working well. if it's grey filling yellow, first mbt is reached, then orange, then red.

the bar is doing its job once quite well. also PSI adds a sad icon which is also permanently displayed if the minor threshold is reached. the game also throws a warning if one threshold is reached. I don't think I need any more layers of information regarding the mood. If players don't act after that many clues, my bar won't save their colony either.

I'm certainly not re-doing the original layout, see screenshot, but I'm open for suggestions..

**Comment by ghost** [comment]
![](https://s18.postimg.io/e8tozyqe1/u_D1pe_MM.png)

Massive rectangular dudes like this is why I need MuzzyUtils. I want more than just a Sad icon.

The minified version of the bar is pretty much impossible to use with this guy btw.

**Comment by ghost** [comment]
I feel like there's a disconnect here though. You say you don't like MuzzyUtils because it's a huge moving eyecatcher. But that's exactly why I like it, and it's why a lot of people like me like it. I don't see what's wrong about it filling the background - it's not like the background was giving me information I particularly needed. I already know what gender they are.

**Comment by tommargar** [comment]
- you already have the option to make it fill the full rect
- the color fills the full rect , thus making it visible all the time what break threshold is reached
- Merlin is nearly reaching his first mental break threshold
- even with muzzy utils the background would be invisible - as it is in your screenshot right now. my mod offers to change the camera offset + zoom. that way you can move the guy around in the window. what else do you want me to take care of? muzzy's bar would also give you ZERO information because NONE of your background is visible..

I don't care how muzzy designed his bar. This is my mod, and I don't want to argue any more why I don't want to revert to a shitty design. Either you like it or start modding yourself. I do this for free and don't want to repeat myself over and over again.

**Comment by ghost** [comment]
Wow.

**Comment by tommargar** [comment]
I'm sorry if I sounded rude, but I had this discussion once before.

**Comment by ghost** [comment]
Do what you want.

**Comment by tommargar** [comment]
I prefer to.
