### ISSUE TITLE
colonist names font size

### ISSUE THREAD

**Issue by jjYBdx4IL** [Killface1980/RW_ColonistBarKF#9]
Hello!

Is there any possibility to adjust the font size used for the colonist names below the colonist bar colonist icons?

And do you know if there is a way to change the UI font size overall? Many users with modern monitors have problems with the current small UI (fonts).

TY!

**Comment by tommargar** [comment]
The label used on the bar is the same label as used everywhere in vanilla. I tried to change it, but have no idea on how to scale it somehow properly. 

But Tynan announced via twitter that A16 UI will have support for high resolution displays, thus I expect some kind of scaling. Otherwise he has to rewrite whe whole UI as it's based on fixed sizes.

**Comment by tommargar** [comment]
is automatically generated, too much work for me to incorporate
